# Generated by Django 3.0.1 on 2020-01-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '网址分类',
                'verbose_name_plural': '网址分类数据库',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('subtitle', models.CharField(max_length=100, verbose_name='描述')),
                ('href', models.TextField(verbose_name='链接')),
                ('image', models.ImageField(upload_to='image', verbose_name='图像')),
                ('date', models.DateField(auto_now_add=True, verbose_name='录入时间')),
                ('href_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UrlsClass')),
            ],
            options={
                'verbose_name': '网址',
                'verbose_name_plural': '网址数据库',
            },
        ),
    ]
