# Generated by Django 3.0.2 on 2020-01-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_urls_sortid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsclass',
            name='sortid',
            field=models.IntegerField(default=5, verbose_name='排序比重'),
        ),
    ]
