# Generated by Django 3.0.2 on 2020-01-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_urlsclass_sortid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name': '公共资源', 'verbose_name_plural': '公共资源数据库'},
        ),
        migrations.AlterModelOptions(
            name='urlsclass',
            options={'verbose_name': '公共资源分类', 'verbose_name_plural': '公共资源分类数据库'},
        ),
        migrations.CreateModel(
            name='PrivateResourcesClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20, verbose_name='分类名')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Urls')),
            ],
            options={
                'verbose_name': '私人资源分类',
                'verbose_name_plural': '私人资源分类数据库',
            },
        ),
    ]
