# Generated by Django 3.0.2 on 2020-01-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200121_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='href_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UrlsClass', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='PrivateResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('subtitle', models.CharField(max_length=100, verbose_name='描述')),
                ('href', models.TextField(verbose_name='链接')),
                ('image', models.ImageField(upload_to='image', verbose_name='图像')),
                ('date', models.DateField(auto_now_add=True, verbose_name='录入时间')),
                ('href_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PrivateResourcesClass', verbose_name='所属分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '私人资源',
                'verbose_name_plural': '私人资源数据库',
            },
        ),
    ]
