# Generated by Django 3.0.2 on 2020-01-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200122_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('date', models.DateField(auto_now=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '关于本站',
                'verbose_name_plural': '关于本站数据库',
            },
        ),
    ]
