# Generated by Django 3.0.2 on 2020-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wechat', verbose_name='二维码')),
            ],
            options={
                'verbose_name': '微信二维码',
                'verbose_name_plural': '微信二维码数据库',
            },
        ),
    ]
